# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Julie Benoit Art
email: spizanky@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Julie Benoit is an artist currently residing in Longmont, CO. Her work is comprised of video, sound, fibers, and some drawing."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.juliebenoitart.com" # the base hostname & protocol for your site

# you can create whatever you'd like and reference it via site.key
twitter_username: mikeriley131
github_username:  mikeriley131

host: localhost

include: ['_assets', '_pages']
exclude: [
  'Gruntfile.js',
  'package.json',
  'to-do.md',
  'node_modules',
  'bower_components',
  '_assets/scss/*',
  '_assets/js/formConfirmation.js',
  '_assets/js/locations.js'
]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"